# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translate.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftranslate.proto\x12\x0btranslation\"$\n\x14TranslateTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"0\n\x15TranslateTextResponse\x12\x17\n\x0ftranslated_text\x18\x01 \x01(\t2n\n\x12TranslationService\x12X\n\rTranslateText\x12!.translation.TranslateTextRequest\x1a\".translation.TranslateTextResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATETEXTREQUEST']._serialized_start=32
  _globals['_TRANSLATETEXTREQUEST']._serialized_end=68
  _globals['_TRANSLATETEXTRESPONSE']._serialized_start=70
  _globals['_TRANSLATETEXTRESPONSE']._serialized_end=118
  _globals['_TRANSLATIONSERVICE']._serialized_start=120
  _globals['_TRANSLATIONSERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
